services:
  # PHP Service
  php:
    build: ./docker/php-fpm
    container_name: php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
      - ./database:/var/www/database
      - ./docker/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app-network

  # Nginx Service
  nginx:
    build: ./docker/nginx
    container_name: nginx-server
    ports:
      - "80:80"
      - "81:81"
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  # Vue.js Frontend
  vue:
    build: ./docker/vue
    container_name: vue-frontend
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge