# Użyj obrazu nginx w wersji opartej na Alpine Linux
FROM nginx:alpine

# Kopiuj plik konfiguracyjny nginx.conf do standardowej lokalizacji konfiguracji Nginx w kontenerze
# Ten plik zawiera wszystkie ustawienia konfiguracyjne dla serwera Nginx
COPY ./nginx.conf /etc/nginx/nginx.conf
